export const authConstants = {
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_ERROR: 'REGISTER_ERROR',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'LOGOUT_ERROR',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  FORGOT_PASSWORD_REQUEST_REQUEST: 'FORGOT_PASSWORD_REQUEST_REQUEST',
  FORGOT_PASSWORD_REQUEST_SUCCESS: 'FORGOT_PASSWORD_REQUEST_SUCCESS',
  FORGOT_PASSWORD_REQUEST_ERROR: 'FORGOT_PASSWORD_REQUEST_ERROR',

  FORGOT_PASSWORD_CONFIRM_REQUEST: 'FORGOT_PASSWORD_CONFIRM_REQUEST',
  FORGOT_PASSWORD_CONFIRM_SUCCESS: 'FORGOT_PASSWORD_CONFIRM_SUCCESS',
  FORGOT_PASSWORD_CONFIRM_ERROR: 'FORGOT_PASSWORD_CONFIRM_ERROR',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',

  CHANGE_EMAIL_REQUEST_REQUEST: 'CHANGE_EMAIL_REQUEST_REQUEST',
  CHANGE_EMAIL_REQUEST_SUCCESS: 'CHANGE_EMAIL_REQUEST_SUCCESS',
  CHANGE_EMAIL_REQUEST_ERROR: 'CHANGE_EMAIL_REQUEST_ERROR',

  CHANGE_EMAIL_CONFIRM_REQUEST: 'CHANGE_EMAIL_CONFIRM_REQUEST',
  CHANGE_EMAIL_CONFIRM_SUCCESS: 'CHANGE_EMAIL_CONFIRM_SUCCESS',
  CHANGE_EMAIL_CONFIRM_ERROR: 'CHANGE_EMAIL_CONFIRM_ERROR',


  LOGOUT: 'USERS_LOGOUT',
};
