export const itemConstants = {

  ACTIVATE_ITEM_SUCCES: 'ACTIVATE_ITEM_SUCCES',
  ACTIVATE_ITEM_ERROR: 'ACTIVATE_ITEM_ERROR',
  ACTIVATE_ITEM_REQUEST: 'ACTIVATE_ITEM_REQUEST',

  CREATE_ITEM_SUCCESS: 'CREATE_ITEM_SUCCESS',
  CREATE_ITEM_REQUEST: 'CREATE_ITEM_REQUEST',
  CREATE_ITEM_ERROR: 'CREATE_ITEM_ERROR',

  CREATE_ITEM_PHOTO_SUCCESS: 'CREATE_ITEM_PHOTO_SUCCESS',
  CREATE_ITEM_PHOTO_REQUEST: 'CREATE_ITEM_PHOTO_REQUEST',
  CREATE_ITEM_PHOTO_ERROR: 'CREATE_ITEM_PHOTO_ERROR',

  UPDATE_ITEM_PHOTO_SUCCESS: 'UPDATE_ITEM_PHOTO_SUCCESS',
  UPDATE_ITEM_PHOTO_REQUEST: 'UPDATE_ITEM_PHOTO_REQUEST',
  UPDATE_ITEM_PHOTO_ERROR: 'UPDATE_ITEM_PHOTO_ERROR',

  DELETE_ITEM_REQUEST: 'DELETE_ITEM_REQUEST',
  DELETE_ITEM_SUCCESS: 'DELETE_ITEM_SUCCESS',
  DELETE_ITEM_ERROR: 'DELETE_ITEM_ERROR',

  DELETE_ITEM_PHOTO_REQUEST: 'DELETE_ITEM_PHOTO_REQUEST',
  DELETE_ITEM_PHOTO_SUCCESS: 'DELETE_ITEM_PHOTO_SUCCESS',
  DELETE_ITEM_PHOTO_ERROR: 'DELETE_ITEM_PHOTO_ERROR',

  UPDATE_ITEM_REQUEST: 'UPDATE_ITEM_REQUEST',
  UPDATE_ITEM_SUCCESS: 'UPDATE_ITEM_SUCCESS',
  UPDATE_ITEM_ERROR: 'UPDATE_ITEM_ERROR',

  MODIFY_ITEM: 'MODIFY_ITEM',

  SELECT_PHOTO: 'SELECT_PHOTO',

  ADD_ITEM_PHOTO_REQUEST: 'ADD_ITEM_PHOTO_REQUEST',
  ADD_ITEM_PHOTO_ERROR: 'ADD_ITEM_PHOTO_ERROR',
  ADD_ITEM_PHOTO_SUCCESS: 'ADD_ITEM_PHOTO_SUCCESS',

  GET_ITEM_INFO_REQUEST: 'GET_ITEM_INFO_REQUEST',
  GET_ITEM_INFO_ERROR: 'GET_ITEM_INFO_ERROR',
  GET_ITEM_INFO_SUCCESS: 'GET_ITEM_INFO_SUCCESS',

  GET_PRIVATE_ITEMS_REQUEST: 'GET_PRIVATE_ITEMS_REQUEST',
  GET_PRIVATE_ITEMS_ERROR: 'GET_PRIVATE_ITEMS_ERROR',
  GET_PRIVATE_ITEMS_SUCCESS: 'GET_PRIVATE_ITEMS_SUCCESS',

  GET_GAME_TAGS_REQUEST: 'GET_GAME_TAGS_REQUEST',
  GET_GAME_TAGS_ERROR: 'GET_GAME_TAGS_ERROR',
  GET_GAME_TAGS_SUCCESS: 'GET_GAME_TAGS_SUCCESS',
};
