export const userConstants = {
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_REQUEST: 'GET_USER_REQUEST',
  GET_USER_ERROR: 'GET_USER_ERROR',

  GET_PRIVATE_PROFILE_SUCCESS: 'GET_PRIVATE_PROFILE_SUCCESS',
  GET_PRIVATE_PROFILE_REQUEST: 'GET_PRIVATE_PROFILE_REQUEST',
  GET_PRIVATE_PROFILE_ERROR: 'GET_PRIVATE_PROFILE_ERROR',

  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  GET_NOTIFICATIONS_REQUEST: 'GET_NOTIFICATIONS_REQUEST',
  GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',

  MODIFY_PRIVATE_PROFILE: 'MODIFY_PRIVATE_PROFILE',

  UPDATE_PRIVATE_PROFILE_SUCCESS: 'UPDATE_PRIVATE_PROFILE_SUCCESS',
  UPDATE_PRIVATE_PROFILE_REQUEST: 'UPDATE_PRIVATE_PROFILE_REQUEST',
  UPDATE_PRIVATE_PROFILE_ERROR: 'UPDATE_PRIVATE_PROFILE_ERROR',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',
};
