export const searchConstants = {

  SEARCH_ITEMS_REQUEST: 'SEARCH_ITEMS_REQUEST',
  SEARCH_ITEMS_ERROR: 'SEARCH_ITEMS_ERROR',
  SEARCH_ITEMS_SUCCESS: 'SEARCH_ITEMS_SUCCESS',

  GET_CITIES_REQUEST: 'GET_CITIES_REQUEST',
  GET_CITIES_ERROR: 'GET_CITIES_ERROR',
  GET_CITIES_SUCCESS: 'GET_CITIES_SUCCESS',

  GET_STATS_REQUEST: 'GET_STATS_REQUEST',
  GET_STATS_ERROR: 'GET_STATS_ERROR',
  GET_STATS_SUCCESS: 'GET_STATS_SUCCESS',

  MODIFY_FILTERS: 'MODIFY_FILTERS',
};
