version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "server.sh"]
    ports:
      - 8000:8000
    container_name: juno
    env_file:
      - .env
    volumes:
      - static_volume:/home/app/web/static

volumes:
  static_volume:
