export const swapsConstants = {

  GET_MSG_LIST_REQUEST: 'GET_MSG_LIST_REQUEST',
  GET_MSG_LIST_ERROR: 'GET_MSG_LIST_ERROR',
  GET_MSG_LIST_SUCCESS: 'GET_MSG_LIST_SUCCESS',

  GET_SWAPS_LIST_REQUEST: 'GET_SWAPS_LIST_REQUEST',
  GET_SWAPS_LIST_ERROR: 'GET_SWAPS_LIST_ERROR',
  GET_SWAPS_LIST_SUCCESS: 'GET_SWAPS_LIST_SUCCESS',

  GET_SWAP_REQUEST: 'GET_SWAP_REQUEST',
  GET_SWAP_ERROR: 'GET_SWAP_ERROR',
  GET_SWAP_SUCCESS: 'GET_SWAP_SUCCESS',


  MODIFY_CURRENT_SWAP: 'MODIFY_CURRENT_SWAP',

  UPDATE_SWAP_REQUEST: 'UPDATE_SWAP_REQUEST',
  UPDATE_SWAP_SUCCESS: 'UPDATE_SWAP_SUCCESS',
  UPDATE_SWAP_ERROR: 'UPDATE_SWAP_ERROR',

  CREATE_SWAP_REQUEST: 'CREATE_SWAP_REQUEST',
  CREATE_SWAP_SUCCESS: 'CREATE_SWAP_SUCCESS',
  CREATE_SWAP_ERROR: 'CREATE_SWAP_ERROR',

  GET_CONV_LIST_REQUEST: 'GET_CONV_LIST_REQUEST',
  GET_CONV_LIST_ERROR: 'GET_CONV_LIST_ERROR',
  GET_CONV_LIST_SUCCESS: 'GET_CONV_LIST_SUCCESS',

  POST_MSG_LIST_REQUEST: 'POST_MSG_LIST_REQUEST',
  POST_MSG_LIST_ERROR: 'POST_MSG_LIST_ERROR',
  POST_MSG_LIST_SUCCESS: 'POST_MSG_LIST_SUCCESS',

  CHANGE_CUR_CONV: 'CHANGE_CUR_CONV',
};
