export const publicItemConstants = {
  SELECT_PHOTO: 'SELECT_PHOTO',

  GET_PUBLIC_ITEM_INFO_REQUEST: 'GET_PUBLIC_ITEM_INFO_REQUEST',
  GET_PUBLIC_ITEM_INFO_ERROR: 'GET_PUBLIC_ITEM_INFO_ERROR',
  GET_PUBLIC_ITEM_INFO_SUCCESS: 'GET_PUBLIC_ITEM_INFO_SUCCESS',

  WRITE_PUBLIC_ITEM_REVIEW_REQUEST: 'WRITE_PUBLIC_ITEM_REVIEW_REQUEST',
  WRITE_PUBLIC_ITEM_REVIEW_ERROR: 'WRITE_PUBLIC_ITEM_REVIEW_ERROR',
  WRITE_PUBLIC_ITEM_REVIEW_SUCCESS: 'WRITE_PUBLIC_ITEM_REVIEW_SUCCESS',
};
