# Generated by Django 3.0.2 on 2020-02-22 08:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sellPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Exchange'), ('R', 'Rent'), ('P', 'Purchase')], default='E', max_length=10, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('activated', models.BooleanField(default=False)),
                ('last_activated', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('stars', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('is_actual_client', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.Item')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', multiselectfield.db.fields.MultiSelectField(choices=[('PRIVATE', 'Private'), ('PUBLIC', 'Public')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('E', 'Exchange'), ('R', 'Rent'), ('P', 'Purchase')], default='E', max_length=10, null=True)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_deals', to=settings.AUTH_USER_MODEL)),
                ('exchange_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exchanges.Item')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='exchanges.Item')),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
