# Generated by Django 3.0.2 on 2020-03-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
