# Generated by Django 3.0.2 on 2020-04-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_auto_20200323_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemreview',
            old_name='item_id',
            new_name='item',
        ),
    ]
