# Generated by Django 3.0.2 on 2020-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_auto_20200405_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='visible',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_activated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
