# Generated by Django 3.0.2 on 2020-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_auto_20200405_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_activated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
