# Generated by Django 3.0.2 on 2020-06-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0008_itemphoto_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tag_type', models.CharField(choices=[('CATEGORY', 'Category'), ('TOPIC', 'Topic')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemphoto',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='swap',
            name='agreed_price',
        ),
        migrations.DeleteModel(
            name='ItemReview',
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='exchanges.GameTag'),
        ),
    ]
