# Generated by Django 3.0.7 on 2020-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0010_auto_20200710_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
