# Generated by Django 3.0.7 on 2020-10-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0013_auto_20200906_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ru_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ru_preview',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ru_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
