# Generated by Django 3.0.7 on 2020-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0014_auto_20201010_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='exchanges.GameTag'),
        ),
    ]
