# Generated by Django 3.0.7 on 2020-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0015_auto_20201018_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AddField(
            model_name='gametag',
            name='ru_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gametag',
            name='uk_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
