# Generated by Django 3.0.7 on 2020-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0016_auto_20201020_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametag',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gametag',
            name='ru_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gametag',
            name='ru_meta_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gametag',
            name='ru_slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='gametag',
            name='uk_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gametag',
            name='uk_meta_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gametag',
            name='uk_slug',
            field=models.SlugField(null=True),
        ),
    ]
