# Generated by Django 3.0.2 on 2020-05-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconversation',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
