# Generated by Django 3.0.7 on 2020-10-05 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_emailmessage_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=240)),
                ('content', models.TextField()),
                ('meta_description', models.CharField(blank=True, max_length=140, null=True)),
                ('meta_title', models.CharField(max_length=140)),
                ('meta_robots', models.CharField(blank=True, max_length=140, null=True)),
                ('open_graph', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=240)),
                ('content', models.TextField()),
                ('published', models.BooleanField()),
                ('featured', models.BooleanField()),
                ('meta_description', models.CharField(blank=True, max_length=140, null=True)),
                ('meta_title', models.CharField(max_length=140)),
                ('meta_robots', models.CharField(blank=True, max_length=140, null=True)),
                ('open_graph', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='support.BlogCategory')),
            ],
        ),
    ]
