# Generated by Django 3.0.7 on 2020-10-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20201005_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='language',
            field=models.CharField(blank=True, choices=[('uk', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='language',
            field=models.CharField(blank=True, choices=[('uk', 'Ukrainian'), ('ru', 'Russian'), ('en', 'English')], max_length=5, null=True),
        ),
    ]
