# Generated by Django 3.0.7 on 2020-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='language',
            field=models.CharField(blank=True, choices=[('uk', 'Ukrainian'), ('ru', 'Russian')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(blank=True, choices=[('uk', 'Ukrainian'), ('ru', 'Russian')], max_length=5, null=True),
        ),
    ]
