# Generated by Django 3.0.7 on 2020-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_auto_20201018_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='image350',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image350',
            field=models.URLField(blank=True, null=True),
        ),
    ]
