# Generated by Django 3.0.7 on 2020-10-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_auto_20201018_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('ru', 'Russian')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='language',
            field=models.CharField(choices=[('uk', 'Ukrainian'), ('ru', 'Russian')], max_length=5, null=True),
        ),
    ]
