# Generated by Django 3.0.7 on 2020-10-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_auto_20201020_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='conversation',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='support.BlogCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('language', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('language', 'slug')},
        ),
        migrations.DeleteModel(
            name='EmailConversation',
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
