# Generated by Django 3.0.2 on 2020-02-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='time_send',
            new_name='time_sent',
        ),
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
