# Generated by Django 3.0.2 on 2020-04-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0007_auto_20200408_1057'),
        ('chat', '0002_auto_20200213_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='swap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exchanges.Swap'),
        ),
    ]
