# Generated by Django 3.0.2 on 2020-04-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_swap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
