# Generated by Django 3.0.2 on 2020-02-23 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200208_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
