# Generated by Django 3.0.2 on 2020-03-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200223_1516'),
    ]

    operations = []
