# Generated by Django 3.0.7 on 2020-06-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0009_auto_20200605_2103'),
        ('users', '0006_auto_20200425_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchanges.Item'),
        ),
    ]
