# Generated by Django 3.0.7 on 2020-07-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_city_searchable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='user',
            name='photo_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
