# Generated by Django 3.0.7 on 2020-08-27 13:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200727_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_services',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
