# Generated by Django 3.0.7 on 2020-08-29 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customnotification',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='customnotification',
            name='users_exclude',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, size=None),
        ),
    ]
